### ISSUE TITLE
recordset never closed.

### ISSUE THREAD

**Issue by danmarsden** [moodle-an-hochschulen/moodle-availability_cohort#1]
https://github.com/moodleuulm/moodle-availability_cohort/blob/376356caaea977341c161ff140f8d067726486a5/locallib.php#L69

probably easier to convert to a records call instead of recordset.

**Comment by Kathrin84** [comment]
Hi @danmarsden,
thank you very much for your review and this issue.
I've changed the code (https://github.com/moodleuulm/moodle-availability_cohort/commit/a8497023d33aea7c4a249432a96d94ba96ee4a33) and released a new version in the plugins repository.
Best, Kathrin
