### ISSUE TITLE
error when copy a course that use availability_cohort

### ISSUE THREAD

**Issue by mojtaba82** [moodle-an-hochschulen/moodle-availability_cohort#10]
Hi. thank you for developing this useful module.
When copy a course that use availability cohort module, copy failed. this error in log appear

Adhoc task failed: core\task\asynchronous_copy_task,Call to undefined function availability_cohort\cohort_get_cohort()
Backtrace:
* line 680 of /availability/classes/tree.php: call to availability_cohort\condition->include_after_restore()
* line 323 of /availability/classes/info.php: call to core_availability\tree->update_after_restore()
* line 926 of /backup/moodle2/restore_stepslib.php: call to core_availability\info->update_after_restore()
* line 34 of /backup/util/plan/restore_execution_step.class.php: call to restore_update_availability->define_execution()
* line 181 of /backup/util/plan/base_task.class.php: call to restore_execution_step->execute()
* line 178 of /backup/util/plan/base_plan.class.php: call to base_task->execute()
* line 168 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
* line 385 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
* line 137 of /lib/classes/task/asynchronous_copy_task.php: call to restore_controller->execute_plan()
* line 341 of /lib/cronlib.php: call to core\task\asynchronous_copy_task->execute()
* line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()

When i remove that activity that use availability cohort module, copy become successful.

**Comment by abias** [comment]
This issue was solved by the PR in #11 .
Thanks again!
