### ISSUE TITLE
restriction by cohort in a forum.

### ISSUE THREAD

**Issue by francelju** [moodle-an-hochschulen/moodle-availability_cohort#14]
when i used the cohort restriction feature, i can still see in the subscribers all students and not just the ones in the cohort

**Comment by abias** [comment]
Hi @francelju ,

I am sorry to tell you, but this plugin just restricts the access to a forum activity and does not influence anything within the forum.
If a course participant is allowed to access the forum (based on the availability condition's settings), he will see the whole data (including all subscribers) in the forum.

Cheers,
Alex
