### ISSUE TITLE
Not all cohorts available in selection menu

### ISSUE THREAD

**Issue by VOOM108** [moodle-an-hochschulen/moodle-availability_cohort#5]
We use v. v3.5-r3 of the plugin in Moodle 3.5 - I can't select from all cohorts, because the list only shows the first 25 of currently 54 global cohorts. That resembles exactly the first page in the cohorts-management section. How can I set the rest of the cohorts with the plugin? (In other areas usually all items are available in the respective menues...)

**Comment by VOOM108** [comment]
Ok, I found the closed issue, but this has been only included in the 3.9-version and needs to be patched by ourselves in older versions the same way in Line 87 of frontend.php, right?

**Comment by abias** [comment]
Indeed, you have to patch your local 3.5 version yourself. 
We do not support 3.5 anymore as you see in https://github.com/moodleuulm/moodle-availability_cohort#moodle-release-support.

Please find the patch on https://github.com/moodleuulm/moodle-availability_cohort/commit/7bc2f46a2ddd78a63739c890370f84d6f8b46dc8.
