### ISSUE TITLE
is this already in core or what do I understand under "cohort"?

### ISSUE THREAD

**Issue by Bambuspony** [moodle-an-hochschulen/moodle-availability_cohort#6]
Hi, there are already groups in core moodle, so for what is the cohort? Sorry, I do not understand the plugin description. Perhaps you can also show a picture with the settings of one activity or participants? Or is the cohort one step higher than a course?
(I'm also fine with an answer in german or PM ;-)

**Comment by lucaboesch** [comment]
Yep. In german, the cohort is "Globale Gruppe". See  https://docs.moodle.org/311/en/Cohorts or https://docs.moodle.org/311/de/Globale_Gruppe
Best,
Luca

**Comment by abias** [comment]
There are two different concepts:
* Groups: These are called 'Gruppen' in german and are sets of course participants within a course
* Cohorts: These are called 'Globale Gruppen' in german and are sets of Moodle users which are defined system-wide or at least on a course category level.

In Moodle core, there is already a availability_group restriction plugin which deals with groups.
This plugin deals with cohorts and is not part of Moodle core.

I hope you understand the concepts now.

Cheers,
Alex
